language: r
r: bioc-devel
sudo: required
cache: packages
apt_packages:
  - ghostscript
r_packages:
  - devtools
  - xtable
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr); codecov()'
